[package]
name = "sing-box-reticulum-bridge"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[features]
default = ["rnode-ble"]
rnode-ble = ["reticulum-rs-transport/rnode-ble", "dep:btleplug"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "sync", "macros", "time"] }
once_cell = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
libc = "0.2"
rand_core = "0.6"
sha2 = "0.10"
hex = "0.4"
reticulum-rs = { git = "https://github.com/IgorShishkin12/LXMF-rs", branch = "main", features = ["core", "transport"] }
reticulum-rs-transport = { package = "reticulum-rs-transport", git = "https://github.com/IgorShishkin12/LXMF-rs", branch = "main" }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["registry", "env-filter"] }
tracing-log = "0.2"
btleplug = { version = "0.11", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
jni = { version = "0.19" }
jni-utils = { version = "0.1.1" }

[dev-dependencies]
serial_test = "3"
